<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Grammar\Parser.cs" Link="Parser.cs" />
    <Compile Include="..\Grammar\Scanner.cs" Link="Scanner.cs" />
    <Compile Include="..\Grammar\AstGen\Parser.cs" Link="AstGen.Parser.cs" />
    <Compile Include="..\Grammar\AstGen\Scanner.cs" Link="AstGen.Scanner.cs" />
  </ItemGroup>

</Project>
